version: '3'

services:
  cowboy-kali:
    container_name: "${APP_NAME:-cowboy-kali}"
    hostname: $HOSTNAME
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/root/cowboy
      - ~/.ssh:/root/.ssh
      - ~/.git:/root/.git
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "${NGINX_HTTP_PORT:-1946}:80"
    environment:
      HOSTNAME: ${HOSTNAME:-cowboy.local}
      APP_NAME: cowboy-kali
      PYTHON_DB_USER: cowboy
      PYTHON_DB_PASS: ${PYTHON_DB_PASS}
      PYTHON_DB_PORT: 2121
      PYTHON_HTTP_PORT: 8000
      NGINX_HTTPS_PORT: 443
      NGINX_HTTP_PORT: ${NGINX_HTTP_PORT:-1946}
    networks:
      - cowboy-kali
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "cowboy", "ping", "--silent" ]
      retries: 3
      timeout: 5s

networks:
  cowboy-kali:
    driver: bridge
