version: '3'

services:
  cowboy-kali:
    container_name: "${APP_NAME:-cowboy-kali}"
    hostname: $HOST_NAME
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/root/cowboy
      - ~/.ssh:/root/.ssh
      - ~/.git:/root/.git
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "${PYTHON_HTTP_PORT:-8000}:8000"
      - "${PYTHON_DB_PORT:-2121}:2121"
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    environment:
      HOST_NAME: ${HOST_NAME:-cowboy.local}
      APP_NAME: ${APP_NAME:-cowboy-kali}
      PYTHON_HTTP_PORT: ${PYTHON_HTTP_PORT:-8000}
      PYTHON_DB_USER: ${PYTHON_DB_USER:-cowboy}
      PYTHON_DB_PASS: ${PYTHON_DB_PASS}
      PYTHON_DB_PORT: ${PYTHON_DB_PORT:-2121}
      NGINX_HTTP_PORT: ${NGINX_HTTP_PORT:-80}
      NGINX_HTTPS_PORT: ${NGINX_HTTPS_PORT:-443}
    networks:
      - cowboy-kali
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "cowboy", "ping" ]
      retries: 3
      timeout: 5s

networks:
  cowboy-kali:
    driver: bridge