#!/bin/bash

echo "- - - - - - - - - - - - - - - - - - -"
echo " Cowboy v0.0.1 (Start)"
echo "- - - - - - - - - - - - - - - - - - -"
echo "whoami: $(whoami)"

nginx -c /etc/nginx/nginx.conf
nginx -s reload

if [ $# -gt 0 ]; then
  exec gosu $(whoami) "$@"
else
  supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi

